In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
reversed_arr=arr[::-1]
reversed_arr

array([6, 5, 4, 3, 2, 1])

In [6]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])


flattened1 = array1.flatten()
flattened1

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [7]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])


comparison = arr1 == arr2

equal = np.array_equal(arr1, arr2)

print(comparison)
print(equal)


[[ True  True]
 [ True  True]]
True


In [8]:
from collections import Counter


x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
most_freq_x = Counter(x).most_common(1)[0]
indices_x = np.where(x == most_freq_x[0])[0]


y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_freq_y = Counter(y).most_common(1)[0]
indices_y = np.where(y == most_freq_y[0])[0]

print(most_freq_x, indices_x)
print(most_freq_y, indices_y)


(np.int64(1), 5) [0 5 7 8 9]
(np.int64(1), 3) [0 1 2]


In [9]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')


total_sum = gfg.sum()

row_sum = gfg.sum(axis=1)

col_sum = gfg.sum(axis=0)

print(total_sum, row_sum, col_sum)


45 [[14]
 [16]
 [15]] [[20  9 16]]


In [11]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])


diag_sum = np.trace(n_array)


eigen_values, eigen_vectors = np.linalg.eig(n_array)


inverse = np.linalg.inv(n_array)


det = np.linalg.det(n_array)

print(diag_sum)
print(eigen_values)
print( eigen_vectors)
print(inverse)
print(det)


176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [12]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

np.dot(p1,q1)

array([[16, 19],
       [26, 31]])

In [14]:
cov1 = np.cov(p1.T, q1.T)
cov1

array([[0.5, 0.5, 1. , 1. ],
       [0.5, 0.5, 1. , 1. ],
       [1. , 1. , 2. , 2. ],
       [1. , 1. , 2. , 2. ]])

In [21]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner = np.inner(x, y)
print("inner : ")
print(inner)

outer = np.outer(x, y)
print("outer : ")
print(outer)


from itertools import product
cartesian = np.array(list(product(x.flatten(), y.flatten())))
print("cartesian:" )
print(cartesian)

inner : 
[[17 52]
 [13 62]]
outer : 
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
cartesian:
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [22]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
abs_array = np.abs(array)


flat = array.flatten()
print(flat)

[ 1 -2  3 -4  5 -6]


In [23]:
p_25=np.percentile(array, 25)
p_25

np.float64(-3.5)

In [24]:
p_50=np.percentile(array,50)
p_50

np.float64(-0.5)

In [25]:
p_75=np.percentile(array,75)
p_75

np.float64(2.5)

In [28]:
percent_col = np.percentile(array, [25, 50, 75], axis=0)
percent_row = np.percentile(array, [25, 50, 75], axis=1)
percent_row



array([[-0.5, -5. ],
       [ 1. , -4. ],
       [ 2. ,  0.5]])

In [29]:
percent_col

array([[-2.75, -0.25, -3.75],
       [-1.5 ,  1.5 , -1.5 ],
       [-0.25,  3.25,  0.75]])

In [30]:
mean_a = np.mean(flat)
median_a = np.median(flat)
std_a = np.std(flat)

mean_a

np.float64(-0.5)

In [32]:
median_a

np.float64(-0.5)

In [33]:
std_a

np.float64(3.8622100754188224)

In [34]:
mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

mean_col
median_col
std_col


mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

mean_row
median_row
std_row

array([2.05480467, 4.78423336])

In [36]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

In [37]:
floors = np.floor(a)
ceilings = np.ceil(a)
truncated = np.trunc(a)
rounded = np.round(a)

print(floors, ceilings, truncated, rounded)


[-2. -2. -1.  0.  1.  1.  3.] [-1. -1. -0.  1.  2.  2.  3.] [-1. -1. -0.  0.  1.  1.  3.] [-2. -2. -0.  0.  2.  2.  3.]


In [38]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)
sorted_indices = np.argsort(array)
smallest_4 = np.partition(array, 3)[:4]
largest_5 = np.partition(array, -5)[-5:]

print(sorted_array, sorted_indices, smallest_4, largest_5)


[ 10  16  16  52  54  62 453] [0 3 4 1 5 2 6] [10 16 16 52] [ 16  52  54  62 453]


In [39]:

array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

int_elements = array[array == array.astype(int)]
float_elements = array[array != array.astype(int)]

print(int_elements, float_elements)


[1. 2. 3. 2.] [1.2 2.2]


In [40]:
from PIL import Image
import numpy as np

def img_to_array(path, save_path='image_array.txt'):
    img = Image.open(path)
    arr = np.array(img)

    if len(arr.shape) == 2:
        print("Grayscale Image")
    elif len(arr.shape) == 3:
        print("RGB Image")

    np.savetxt(save_path, arr.reshape(-1, arr.shape[-1]) if len(arr.shape) == 3 else arr, fmt='%d')
    return arr
